"""Stable exception taxonomy."""

MISSING_IN_BANK = "MISSING_IN_BANK"
UNKNOWN_BANK_CREDIT = "UNKNOWN_BANK_CREDIT"
PAID_ORDER_MISSING_FROM_GATEWAY = "PAID_ORDER_MISSING_FROM_GATEWAY"
AMOUNT_MISMATCH_BEYOND_TOL = "AMOUNT_MISMATCH_BEYOND_TOL"
DATE_OUT_OF_WINDOW = "DATE_OUT_OF_WINDOW"
AMBIGUOUS_TIE = "AMBIGUOUS_TIE"
AMBIGUOUS_COMBINED = "AMBIGUOUS_COMBINED"
DUPLICATE_UTR = "DUPLICATE_UTR"
DUPLICATE_BANK_LINE = "DUPLICATE_BANK_LINE"
UTR_CONFLICT_IN_BATCH = "UTR_CONFLICT_IN_BATCH"
UNSUPPORTED_MEMBER_IN_BATCH = "UNSUPPORTED_MEMBER_IN_BATCH"
NARRATION_UNPARSEABLE = "NARRATION_UNPARSEABLE"
FEE_MODEL_VIOLATION = "FEE_MODEL_VIOLATION"
ORPHAN_REFUND = "ORPHAN_REFUND"
INGEST_REJECT = "INGEST_REJECT"

ALL_CODES = frozenset(name for name, value in globals().copy().items()
                      if name.isupper() and isinstance(value, str))
